Add poweroff and nowait FAI_FLAGS.
This allow a different handling for FAI when finishing or aborting an
installation.  The default can also be changed editing the FAI_ABORT
variable in fai.conf.

This also installs a faipoweroff symlink to faireboot, which powers off
the host instead of rebooting it.

nowait is introduced becauce reboot halts the host until enter is
pressed, so this combination allows to poweroff or reboot immediately
when finished.

diff --git a/lib/subroutines b/lib/subroutines
--- a/lib/subroutines
+++ b/lib/subroutines
@@ -360,9 +360,28 @@ define_fai_flags() {
     for flag in $FAI_FLAGS; do
         # define this flag as 1
         eval "flag_$flag=1"
+        case $flag in
+            poweroff|reboot) export FAI_ABORT=$flag ;;
+            halt)
+                export FAI_ABORT=poweroff
+                flag_poweroff=1
+                ;;
+            wait) flag_nowait=0 ;;
+            nowait) flag_wait=0 ;;
+        esac
     done
     [ "$flag_verbose" ] && verbose=1 # for backward compability
     [ "$flag_debug" ]   && debug=1   # for backward compability
+    [ "$flag_poweroff" -o "$flag_reboot" ] && flag_nowait=1
+    [ "$flag_wait" = "1" ] && flag_nowait=0
+
+    if [ "$FAI_ABORT" != "poweroff" ]; then
+        unset flag_poweroff
+        trap 'echo "Now rebooting";faireboot' INT QUIT
+    else
+        unset flag_reboot
+        trap 'echo "Now shutting down";faipoweroff' INT QUIT
+    fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ### BEGIN SUBROUTINE INFO
@@ -590,22 +609,42 @@ task_faiend() {
 
     local dir cdromdevice
     [ $do_init_tasks -eq 0 ] && return 0
-    wait_for_jobs
-    : ${flag_reboot:=0}
-    : ${flag_halt:=0}
 
-    # reboot/halt without prompting if FAI_FLAG reboot or halt is set and errors are found
-    # wait for keypress if error is found and neither flag reboot nor halt is set
-    if [ -s $LOGDIR/error.log -a "$flag_reboot" -eq 0 -a "$flag_halt" -eq 0 ]; then
-        echo "Press <RETURN> to reboot."
-        read
+    # initialize empty flags
+    [ -z "${flag_nowait:=0}" ] && flag_nowait=0
+
+    wait_for_jobs
+    sendmon "TASKEND faiend 0"
+
+    # quit without prompting if FAI_FLAG nowait is set
+    if [ "$flag_nowait" -lt "1" ]; then
+        WAIT_TEXT="Press <RETURN> to '${FAI_ABORT}'."
+        if [ -x /bin/plymouth ] && plymouth --ping; then
+            plymouth show-splash
+            plymouth message --text="${WAIT_TEXT}"
+            plymouth watch-keystroke | read nunya
+        elif [ -x /sbin/usplash_write ]; then
+            /sbin/usplash_write "INPUTENTER ${WAIT_TEXT}"
+            read nunya < /dev/.initramfs/usplash_outfifo
+        else
+            echo "${WAIT_TEXT}"
+            read nunya
+        fi
     else
-        sleep 10
+        if [ "$FAI_ABORT" != "poweroff" ]; then
+            echo "Rebooting $HOSTNAME now"
+        else
+            echo "Powering off $HOSTNAME now"
+        fi
     fi
 
-    sendmon "TASKEND faiend 0"
-    echo "Rebooting $HOSTNAME now"
-    sendmon "TASKEND reboot 0"
+    # inform faimond of last action
+    if [ "$FAI_ABORT" != "poweroff" ]; then
+        sendmon "TASKEND reboot 0"
+    else
+        sendmon "TASKEND poweroff 0"
+    fi
+
     cd /
     sync
 
@@ -616,18 +655,17 @@ task_faiend() {
 #! /bin/bash
  device=$1
 eject -m /dev/$device 2>/dev/null >/dev/null
-echo "Remove CDROM and press <RETURN> to continue reboot"
+echo "Remove CDROM, close tray and press <RETURN> to continue $FAI_ABORT"
 read
 eject -t /dev/$device 2>/dev/null >/dev/null
 EOF
 
-        #reboot or halt?
-        if [ "$flag_halt" -gt "0" ]; then
-            echo "exec halt -dfp" >> $target/tmp/rebootCD
-        else
+        #reboot or poweroff?
+        if [ "$FAI_ABORT" != "poweroff" ]; then
             echo "exec reboot -df" >> $target/tmp/rebootCD
+        else
+            echo "exec poweroff -df" >> $target/tmp/rebootCD
         fi
-
 
         chmod +x $target/tmp/rebootCD
         sync
@@ -642,14 +680,11 @@ EOF
     fi
     umount $FAI_ROOT/proc
     umount -arf 2>/dev/null
-
-    # reboot or halt?
-    if [ "$flag_halt" -gt "0" ]; then
-        exec halt -dfip;
+    if [ "$FAI_ABORT" != "poweroff" ]; then
+      exec reboot -dfi
     else
-        exec reboot -dfi;
+      exec poweroff -dfi
     fi
-
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 task_install() {
