Move error strings to subroutines-error.
Moves the error strings to fai_strerror function in
subroutines-error to make better use of the error codes and
to consolidate error messages.

diff --git a/lib/subroutines b/lib/subroutines
--- a/lib/subroutines
+++ b/lib/subroutines
@@ -30,6 +30,9 @@
 
 # source this file, then you have these function available in the shell
 
+# get the error codes
+. /usr/lib/fai/subroutines-error
+
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 die() {
 
@@ -158,6 +161,7 @@ stop_fai_installation() {
     # this subroutine should directly stop the installation process
     sendmon "TASKERROR $taskname $task_error_code"
     echo "Error in task $taskname. Traceback: $task_error_func" >&2
+    [ -n "$task_error_msg" ] && echo "Error message: $task_error_msg" >&2
     die "FATAL ERROR. Installation stopped."
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -175,23 +179,56 @@ task_error() {
 
     task_error_func=${FUNCNAME[*]}
     task_error_code=$1
-    task_error_msg=$2
-    [ $1 -gt $task_error_code_max ] && task_error_code_max=$1
-    [ $task_error_code -gt $STOP_ON_ERROR ] && stop_fai_installation
+    shift
+
+    # Get the error message in $task_error_msg
+    fai_strerror $@
+
+    [ $task_error_code -ge $STOP_ON_ERROR ] && stop_fai_installation
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ### BEGIN SUBROUTINE INFO
 # Provides-Var:      $task_error_code
-# Required-Var:      $1 $2 $3 $task_error_code
+# Required-Var:      $1
 # Short-Description: convenience function for exitcode errors
 # Long-Description: 
 #   $1 = the returncode
 #   $2 = the FAI error code
-#   $3 = the error message
+#   $@ = error variables
 ### END SUBROUTINE INFO
 
 exitcode_error() {
-    [ $1 -ne 0 ] && task error $2 $3
+
+    if [ $1 -ne 0 ]; then
+        shift
+        task error $@
+    fi
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+### BEGIN SUBROUTINE INFO
+# Provides-Var:      $task_error_code $GETCONFIG_TOOL
+# Required-Var:      $1
+# Short-Description: convenience function for exitcode errors
+# Long-Description:
+#   $1 = the returncode
+#   $2 = the FAI error code
+#   $@ = error variables
+### END SUBROUTINE INFO
+
+exitcode_error_getconfig() {
+
+    local ecode=$1
+    local fai_code=$2
+
+    if [ -z $GETCONFIG_TOOL ]; then
+        echo "\$GETCONFIG_TOOL not set. This function should just be called from get-config-dir-* helpers!"
+        return
+    fi
+
+    if [ $ecode -ne 0 ]; then
+        shift ; shift
+        task error $fai_code $GETCONFIG_TOOL $ecode $@
+    fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ### BEGIN SUBROUTINE INFO
@@ -345,7 +382,7 @@ task_setup() {
 task_action() {
 
     if [ -z "$FAI_ACTION" ]; then
-        task error 910 "No action in \$FAI_ACTION defined."
+        task error 900
         exit
     fi
 
@@ -353,7 +390,7 @@ task_action() {
     case $FAI_ACTION in
         install)
             if [ $do_init_tasks -eq 0 ]; then
-                task error 920 "Cowardly refusing to run a FAI installation on a running system."
+                task error 901
                 return
             fi
             echo Performing FAI installation. All data may be overwritten!
@@ -383,7 +420,7 @@ task_action() {
                 echo "Calling user defined action: $FAI_ACTION"
                 $FAI/hooks/$FAI_ACTION
             else
-                task error 922 "User defined action /hooks/$FAI_ACTION not found."
+                task error 902 "$FAI_ACTION"
             fi
             ;;
     esac
@@ -401,7 +438,7 @@ task_defclass() {
     if [ ! -d $FAI/class ]; then
         echo "Subdirectory $FAI/class missing in config space. Following subdirectories are found:"
         find $FAI -maxdepth 1 -type d -printf "%p\n"
-        task error 730 "Subdirectory 'class' missing in config space ($FAI)."
+        task error 907 "$FAI"
     fi
 
     # new script for defining classes; variables imported: $LOGDIR, $verbose, $debug
@@ -413,7 +450,7 @@ task_defclass() {
         classes=$cmdlineclasses
     elif [ ! -f /var/lib/fai/FAI_CLASSES ]; then
         # use classes defined at installation time
-        task error 740 "Try to read classes from /var/lib/fai/FAI_CLASSES. Failed. Aborting."
+        task error 903
     else
         classes=$(< /var/lib/fai/FAI_CLASSES)
     fi
@@ -469,20 +506,20 @@ task_defvar() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 task_mountdisks() {
 
-    [ ! -f $LOGDIR/fstab ] && task error 750 "No $LOGDIR/fstab created."
+    [ ! -f $LOGDIR/fstab ] && task error 750 "$LOGDIR"
     # mount swap space
     local sd
     for sd in $SWAPLIST; do
         swapon -p1 $sd && [ "$verbose" ] && echo "Enable swap device $sd"
     done
     mount2dir $FAI_ROOT $LOGDIR/fstab
-    exitcode_error $? 885 "mountdisks failed"
+    exitcode_error $? 860
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 task_configure() {
 
     fai-do-scripts $FAI/scripts
-    exitcode_error $? 420 "FAI scripts failed"
+    exitcode_error $? 420
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 task_tests() {
@@ -492,7 +529,7 @@ task_tests() {
         # check if any test failed
         if [ -f $LOGDIR/test.log ]; then
             if grep -q "FAILED with " $LOGDIR/test.log; then
-                task error 312 "Tests failed"
+                task error 312
                 return 1
             fi
         fi
@@ -605,7 +642,7 @@ task_install() {
         echo "Error while executing commands in subshell." >&2
         echo -n "$stamp was not removed. PID of running process: "
         cat $stamp
-        task error 930 "Task install failed. Please look at the log files in $LOGDIR for errors."
+        task error 904 "install" "$LOGDIR"
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -665,14 +702,14 @@ task_dirinstall() {
         echo "Error while executing commands in subshell." >&2
         echo -n "$stamp was not removed. PID of running process: "
         cat $stamp
-        task error 870 "Please look at the log files in $LOGDIR for errors."
+        task error 904 "dirinstall" "$LOGDIR"
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 task_softupdate() {
 
     stamp=/var/run/fai/fai_softupdate_is_running
-    [ -f "$stamp" ] && task error 900 "Lock file $stamp found. Another fai softupdate is already running. Aborting."
+    [ -f "$stamp" ] && task error 905 "$stamp"
     echo $$ > $stamp
     trap "rm -f $stamp" INT QUIT EXIT
 
@@ -703,7 +740,7 @@ task_softupdate() {
         echo "Error while executing commands in subshell." >&2
         echo -n "$stamp was not removed. PID of running process: "
         cat $stamp
-        task error 900 "Please look at the log files in $LOGDIR for errors."
+        task error 904 "softupdate" "$LOGDIR"
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -796,7 +833,7 @@ task_confdir() {
     fi
 
     get-config-dir || {
-        task error 900 "Problems accessing the config space."
+        task error 906
     }
 
     # now you have enough time to make changes to the config space
@@ -826,7 +863,7 @@ task_partition() {
     # partitioning tool must create $LOGDIR/disk_var.sh file
     if [ ! -s $LOGDIR/disk_var.sh ]; then
         cat $LOGDIR/format.log
-        task error 710 "Partitioning tool did not create $LOGDIR/disk_var.sh file."
+        task error 850 "$LOGDIR"
     fi
     # now define variable for root and boot partition and boot device
     . $LOGDIR/disk_var.sh
@@ -876,9 +913,9 @@ task_extrbase() {
         # if no base file was extracted, call debootstrap
         if [ ! -d $FAI_ROOT/etc ]; then
             echo "No base file found. Calling debootstrap."
-            [ -z "$FAI_DEBOOTSTRAP" ] && task error 801 "\$FAI_DEBOOTSTRAP undefined. Aborting"
+            [ -z "$FAI_DEBOOTSTRAP" ] && task error 801
             call_debootstrap $FAI_DEBOOTSTRAP
-            exitcode_error $? 803 "Debootstraping failed"
+            exitcode_error $? 803
         fi
     fi
     # now we can copy fstab
@@ -905,14 +942,14 @@ mount_mirror() {
     if mount $romountopt $FAI_DEBMIRROR ${FAI_ROOT}${MNTPOINT}; then
       [ "$debug" ] && echo "Mirror mounted from $FAI_DEBMIRROR to ${FAI_ROOT}${MNTPOINT}"
     else
-      task error 810 "Can't mount $FAI_DEBMIRROR"
+      task error 810 "$FAI_DEBMIRROR"
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 task_debconf () {
 
     if [ ! -d $FAI/debconf ]; then
-        task error 400 "Can't find debconf directory in config space. Skipping preseeding."
+        task error 400
         return
     fi
     fai-debconf $FAI/debconf
@@ -1006,10 +1043,10 @@ task_updatebase() {
 
     if [ "$verbose" ]; then
         updatebase </dev/null 2>&1 | tee -a $LOGDIR/software.log
-        exitcode_error ${PIPESTATUS[0]} 474 "Updatebase failed: ${PIPESTATUS[0]}"
+        exitcode_error ${PIPESTATUS[0]} 474 "${PIPESTATUS[0]}"
     else
         updatebase </dev/null >> $LOGDIR/software.log 2>&1
-        exitcode_error $? 474 "Updatebase failed: $?"
+        exitcode_error $? 474 "$?"
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -1018,18 +1055,18 @@ task_instsoft() {
     echo "Installing software may take a while"
     if [ "$debug" ]; then
         install_packages | tee -a $LOGDIR/software.log
-        exitcode_error ${PIPESTATUS[0]} 471 "install_packages failed: ${PIPESTATUS[0]}"
+        exitcode_error ${PIPESTATUS[0]} 471 "${PIPESTATUS[0]}"
     elif [ "$verbose" ]; then
         install_packages </dev/null 2>&1 | tee -a $LOGDIR/software.log
-        exitcode_error ${PIPESTATUS[0]} 471 "install_packages failed: ${PIPESTATUS[0]}"
+        exitcode_error ${PIPESTATUS[0]} 471 "${PIPESTATUS[0]}"
     else
         install_packages </dev/null >> $LOGDIR/software.log 2>&1
-        exitcode_error $? 471 "install_packages failed: $?"
+        exitcode_error $? 471 "$?"
     fi
     # This almost indicates an error
-    egrep "^E:" $LOGDIR/software.log && task error 472 "install_packages: various error messages"
-    grep "Couldn't find any package whose name or description matched" $LOGDIR/software.log && task error 321 "install_packages: packages missing"
-    grep -q "E: Sub-process /usr/bin/dpkg returned an error code" $LOGDIR/software.log && task error 920 "install_packages: dpkg errors"
+    egrep "^E:" $LOGDIR/software.log && task error 472
+    grep "Couldn't find any package whose name or description matched" $LOGDIR/software.log && task error 321
+    grep -q "E: Sub-process /usr/bin/dpkg returned an error code" $LOGDIR/software.log && task error 700
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 task_finish() {
@@ -1070,8 +1107,7 @@ task_chboot() {
     frsh="$remotesh -l $LOGUSER ${SERVER}"
 
     if [ -z "$SERVER" ] ; then
-        echo "SERVER not defined. Can't change network boot configuration"
-        task error 2
+        task error 500
         doexit=1
     fi
     [ $doexit -eq 1 ] && return
@@ -1080,7 +1116,7 @@ task_chboot() {
     # first test if rsh to server works
     $frsh true >/dev/null 2>&1
     if [ $? -ne 0 ]; then
-        task error 300 "$frsh failed. Can't call fai-chboot on the install server."
+        task error 501 "$frsh"
     else
         if [ -n "$nexttest" ]; then
                 # for test sequences, we want the system to reinstall immediately with
