Change lot of die calls to task error calls.

diff --git a/lib/subroutines b/lib/subroutines
--- a/lib/subroutines
+++ b/lib/subroutines
@@ -35,7 +35,7 @@ die() {
 
     # echo comment and exit installation
     task savelog
-    echo "$@"
+    echo "$@" >&2
     if [ X$FAI_ACTION = Xinstall ]; then
         exec bash -i
     else
@@ -156,24 +156,42 @@ wait_for_jobs() {
 stop_fai_installation() {
 
     # this subroutine should directly stop the installation process
-    sendmon "TASKEND $taskname $task_error_code"
+    sendmon "TASKERROR $taskname $task_error_code"
     echo "Error in task $taskname. Traceback: $task_error_func" >&2
     die "FATAL ERROR. Installation stopped."
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ### BEGIN SUBROUTINE INFO
-# Provides-Var:      $task_error_code
-# Required-Var:      $1 $2 $task_error_code
-# Short-Description: save the maximum error code,
-# Short-Description: $1 is the error that will be saved unless $2 is zero
+# Provides-Var:      $task_error_code $task_error_func $task_error_msg
+# Required-Var:      $1
+# Suggests-Var:      $2
+# Short-Description: error task handler
+# Long-Description:
+#   $1 = the FAI error code
+#   $2 = the error message
 ### END SUBROUTINE INFO
 
 task_error() {
 
-    [ X$2 = X0 ] && return
     task_error_func=${FUNCNAME[*]}
-    [ $1 -gt $task_error_code ] && task_error_code=$1
+    task_error_code=$1
+    task_error_msg=$2
+    [ $1 -gt $task_error_code_max ] && task_error_code_max=$1
     [ $task_error_code -gt $STOP_ON_ERROR ] && stop_fai_installation
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+### BEGIN SUBROUTINE INFO
+# Provides-Var:      $task_error_code
+# Required-Var:      $1 $2 $3 $task_error_code
+# Short-Description: convenience function for exitcode errors
+# Long-Description: 
+#   $1 = the returncode
+#   $2 = the FAI error code
+#   $3 = the error message
+### END SUBROUTINE INFO
+
+exitcode_error() {
+    [ $1 -ne 0 ] && task error $2 $3
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ### BEGIN SUBROUTINE INFO
@@ -201,8 +219,11 @@ task() {
     else
         echo "Calling task_$taskname"
         sendmon "TASKBEGIN $taskname"
-        task_error_code=0   # task can set this variable to indicate an error
+        # tasks can set these variables to indicate an error
+        task_error_code=0
         task_error_func=''
+        task_error_msg=''
+
         task_$taskname "$@"
         sendmon "TASKEND $taskname $task_error_code"
         if [ "$task_error_code" -ne 0 ] ; then
@@ -324,9 +345,7 @@ task_setup() {
 task_action() {
 
     if [ -z "$FAI_ACTION" ]; then
-        echo "No action in \$FAI_ACTION defined."
-        sendmon "TASKERROR action 21"
-        task_faiend
+        task error 910 "No action in \$FAI_ACTION defined."
         exit
     fi
 
@@ -334,7 +353,7 @@ task_action() {
     case $FAI_ACTION in
         install)
             if [ $do_init_tasks -eq 0 ]; then
-                echo "Cowardly refusing to run a FAI installation on a running system."
+                task error 920 "Cowardly refusing to run a FAI installation on a running system."
                 return
             fi
             echo Performing FAI installation. All data may be overwritten!
@@ -364,9 +383,7 @@ task_action() {
                 echo "Calling user defined action: $FAI_ACTION"
                 $FAI/hooks/$FAI_ACTION
             else
-                echo "ERROR: User defined action $FAI/hooks/$FAI_ACTION not found." >&2
-                sendmon "TASKERROR action 22"
-                task_faiend
+                task error 922 "User defined action /hooks/$FAI_ACTION not found."
             fi
             ;;
     esac
@@ -382,10 +399,9 @@ task_action() {
 task_defclass() {
 
     if [ ! -d $FAI/class ]; then
-        sendmon "TASKERROR defclass 21"
         echo "Subdirectory $FAI/class missing in config space. Following subdirectories are found:"
         find $FAI -maxdepth 1 -type d -printf "%p\n"
-        die "Aborting."
+        task error 730 "Subdirectory 'class' missing in config space ($FAI)."
     fi
 
     # new script for defining classes; variables imported: $LOGDIR, $verbose, $debug
@@ -397,7 +413,7 @@ task_defclass() {
         classes=$cmdlineclasses
     elif [ ! -f /var/lib/fai/FAI_CLASSES ]; then
         # use classes defined at installation time
-        die "Try to read classes from /var/lib/fai/FAI_CLASSES. Failed. Aborting."
+        task error 740 "Try to read classes from /var/lib/fai/FAI_CLASSES. Failed. Aborting."
     else
         classes=$(< /var/lib/fai/FAI_CLASSES)
     fi
@@ -453,23 +469,20 @@ task_defvar() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 task_mountdisks() {
 
-    [ ! -f $LOGDIR/fstab ] && die "No $LOGDIR/fstab created."
+    [ ! -f $LOGDIR/fstab ] && task error 750 "No $LOGDIR/fstab created."
     # mount swap space
     local sd
     for sd in $SWAPLIST; do
         swapon -p1 $sd && [ "$verbose" ] && echo "Enable swap device $sd"
     done
     mount2dir $FAI_ROOT $LOGDIR/fstab
-    if [ "$?" -ne 0 ]; then
-        sendmon "TASKERROR mountdisks 885"
-        task error 885
-    fi
+    exitcode_error $? 885 "mountdisks failed"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 task_configure() {
 
     fai-do-scripts $FAI/scripts
-    task error 420 $?
+    exitcode_error $? 420 "FAI scripts failed"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 task_tests() {
@@ -479,8 +492,7 @@ task_tests() {
         # check if any test failed
         if [ -f $LOGDIR/test.log ]; then
             if grep -q "FAILED with " $LOGDIR/test.log; then
-                sendmon "TASKERROR tests 312"
-                task error 312
+                task error 312 "Tests failed"
                 return 1
             fi
         fi
@@ -593,8 +605,7 @@ task_install() {
         echo "Error while executing commands in subshell." >&2
         echo -n "$stamp was not removed. PID of running process: "
         cat $stamp
-        sendmon "TASKERROR install 21"
-        die "Please look at the log files in $LOGDIR for errors." >&2
+        task error 930 "Task install failed. Please look at the log files in $LOGDIR for errors."
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -654,15 +665,14 @@ task_dirinstall() {
         echo "Error while executing commands in subshell." >&2
         echo -n "$stamp was not removed. PID of running process: "
         cat $stamp
-        sendmon "TASKERROR install 21"
-        die "Please look at the log files in $LOGDIR for errors." >&2
+        task error 870 "Please look at the log files in $LOGDIR for errors."
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 task_softupdate() {
 
     stamp=/var/run/fai/fai_softupdate_is_running
-    [ -f "$stamp" ] && die "Lock file $stamp found. Another fai softupdate is already running. Aborting."
+    [ -f "$stamp" ] && task error 900 "Lock file $stamp found. Another fai softupdate is already running. Aborting."
     echo $$ > $stamp
     trap "rm -f $stamp" INT QUIT EXIT
 
@@ -693,8 +703,7 @@ task_softupdate() {
         echo "Error while executing commands in subshell." >&2
         echo -n "$stamp was not removed. PID of running process: "
         cat $stamp
-        sendmon "TASKERROR softupdate 21"
-        die "Please look at the log files in $LOGDIR for errors." >&2
+        task error 900 "Please look at the log files in $LOGDIR for errors."
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -787,8 +796,7 @@ task_confdir() {
     fi
 
     get-config-dir || {
-        echo "Problems accessing the config space."
-        die ""
+        task error 900 "Problems accessing the config space."
     }
 
     # now you have enough time to make changes to the config space
@@ -818,9 +826,7 @@ task_partition() {
     # partitioning tool must create $LOGDIR/disk_var.sh file
     if [ ! -s $LOGDIR/disk_var.sh ]; then
         cat $LOGDIR/format.log
-        sendmon "TASKERROR partition 21"
-        task error 710
-        die "Partitioning tool did not create $LOGDIR/disk_var.sh file."
+        task error 710 "Partitioning tool did not create $LOGDIR/disk_var.sh file."
     fi
     # now define variable for root and boot partition and boot device
     . $LOGDIR/disk_var.sh
@@ -870,9 +876,9 @@ task_extrbase() {
         # if no base file was extracted, call debootstrap
         if [ ! -d $FAI_ROOT/etc ]; then
             echo "No base file found. Calling debootstrap."
-            [ -z "$FAI_DEBOOTSTRAP" ] && die "$FAI_DEBOOTSTRAP undefined. Aborting"
+            [ -z "$FAI_DEBOOTSTRAP" ] && task error 801 "\$FAI_DEBOOTSTRAP undefined. Aborting"
             call_debootstrap $FAI_DEBOOTSTRAP
-            task error 801 $?
+            exitcode_error $? 803 "Debootstraping failed"
         fi
     fi
     # now we can copy fstab
@@ -899,16 +905,14 @@ mount_mirror() {
     if mount $romountopt $FAI_DEBMIRROR ${FAI_ROOT}${MNTPOINT}; then
       [ "$debug" ] && echo "Mirror mounted from $FAI_DEBMIRROR to ${FAI_ROOT}${MNTPOINT}"
     else
-      sendmon "TASKERROR mirror $?"
-      die "Can't mount $FAI_DEBMIRROR"
+      task error 810 "Can't mount $FAI_DEBMIRROR"
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 task_debconf () {
 
     if [ ! -d $FAI/debconf ]; then
-        echo "Can't find debconf directory $FAI/debconf. Skipping preseeding."
-        task error 2
+        task error 400 "Can't find debconf directory in config space. Skipping preseeding."
         return
     fi
     fai-debconf $FAI/debconf
@@ -1002,10 +1006,10 @@ task_updatebase() {
 
     if [ "$verbose" ]; then
         updatebase </dev/null 2>&1 | tee -a $LOGDIR/software.log
-        task error 474 ${PIPESTATUS[0]}
+        exitcode_error ${PIPESTATUS[0]} 474 "Updatebase failed: ${PIPESTATUS[0]}"
     else
         updatebase </dev/null >> $LOGDIR/software.log 2>&1
-        task error 474 $?
+        exitcode_error $? 474 "Updatebase failed: $?"
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -1014,18 +1018,18 @@ task_instsoft() {
     echo "Installing software may take a while"
     if [ "$debug" ]; then
         install_packages | tee -a $LOGDIR/software.log
-        task error 471 ${PIPESTATUS[0]}
+        exitcode_error ${PIPESTATUS[0]} 471 "install_packages failed: ${PIPESTATUS[0]}"
     elif [ "$verbose" ]; then
         install_packages </dev/null 2>&1 | tee -a $LOGDIR/software.log
-        task error 471 ${PIPESTATUS[0]}
+        exitcode_error ${PIPESTATUS[0]} 471 "install_packages failed: ${PIPESTATUS[0]}"
     else
         install_packages </dev/null >> $LOGDIR/software.log 2>&1
-        task error 471 $?
+        exitcode_error $? 471 "install_packages failed: $?"
     fi
     # This almost indicates an error
-    egrep "^E:" $LOGDIR/software.log && task error 472
-    grep "Couldn't find any package whose name or description matched" $LOGDIR/software.log && task error 321
-    grep -q "E: Sub-process /usr/bin/dpkg returned an error code" $LOGDIR/software.log && task error 620
+    egrep "^E:" $LOGDIR/software.log && task error 472 "install_packages: various error messages"
+    grep "Couldn't find any package whose name or description matched" $LOGDIR/software.log && task error 321 "install_packages: packages missing"
+    grep -q "E: Sub-process /usr/bin/dpkg returned an error code" $LOGDIR/software.log && task error 920 "install_packages: dpkg errors"
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 task_finish() {
@@ -1076,8 +1080,7 @@ task_chboot() {
     # first test if rsh to server works
     $frsh true >/dev/null 2>&1
     if [ $? -ne 0 ]; then
-        task error 3
-        echo "WARNING: $frsh failed. Can't call fai-chboot on the install server." >&2
+        task error 300 "$frsh failed. Can't call fai-chboot on the install server."
     else
         if [ -n "$nexttest" ]; then
                 # for test sequences, we want the system to reinstall immediately with
